type: "Folder"

props:
- name: "app-name"
  type: "String"

- name: "device-type"
  type: "String"

- name: "lan-ip-address"
  type: "String"

- name: "mac-address"
  type: "String"

- name: "username"
  type: "String"

