type: "Folder"

props:
- name: "created-at"
  type: "String"

- name: "get-qr-url"
  type: "Function"
  target: "get-qr-url"

- name: "icon"
  type: "String"

- name: "public"
  type: "String"

- name: "secret"
  type: "String"

- name: "send-message"
  type: "Function"
  target: "send-message"

- name: "svc-name"
  type: "String"

