type: "Folder"

props:
- name: "hostname"
  type: "String"

- name: "port"
  type: "String"

- name: "nickname"
  type: "String"

- name: "password"
  type: "String"
  optional: true

- name: "username"
  type: "String"
  optional: true

- name: "full-name"
  type: "String"
  optional: true

- name: "ident"
  type: "String"
  optional: true

