type: "Folder"

props:
- name: "app-name"
  type: "String"

- name: "namespace"
  type: "Folder"

- name: "processes"
  type: "Folder"
  target: "process"

- name: "restart"
  type: "Function"
  target: "restart-app"

- name: "session"
  type: "session"

- name: "start-routine"
  type: "Function"
  target: "start-routine"

- name: "status"
  type: "String"

native-props:
- name: "ctx"
  type: "base.Context"

- name: "nextPid"
  type: "int"

